torproject/community

content/relay-operations/technical-setup/bridge/docker/contents.lr
The instructions stopped working because docker messed up its command
line parsing: <https://github.com/docker/cli/issues/1962>
Besides, lektor doesn't like backslashes in code blocks.
=> Remove instructions for manual invokation.

content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr
When I read this I was stumped for a while by the fact that the same name was used for what I believe should be two different values. TODO was used for both the ORPort and the obfs4 port.. I tried to make it clear that these should be two different ports. Also, you install obfs4 into /usr/local/bin but then configured tor to use /usr/bin.
Some issues I was unable to resolve:
1. on CentOS Linux release 7.6.1810 I was unable to install obfs4 using 'go get'.
```
go get gitlab.com/yawning/obfs4.git/obfs4proxy
cd .; git clone https://gitlab.com/yawning/utls /tmp/tmp.HMbPtKs8RV/src/gitlab.com/yawnin/utls.git
error: RPC failed; result=22, HTTP code = 404
fatal: The remote end hung up unexpectedly
package gitlab.com/yawning/utls.git: exit status 128
```
2. On Fedora 30 I was able to install …
=> Fix port number ambiguity and path issue

content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr
I'm still investigating whether or not you run into the same problems that I did on Fedora in other selinux enabled systems (CentOS/RHEL). But I noticed this little thing as well, so I figured I might as well change it
=> Change small typo

content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr
So this is what I needed to do in order to get my fedora server up and running as a bridge, and I've added these instructions as if these problems only affect Fedora users, but I would be surprised if that's the case, because the alternative ports that are encouraged in this guide for ORPort and ServerTransportListenAddr are exactly what selinux is supposed to stop. Because of that, I'd imagine that this would function the same on CentOS SUSE and RHEL.
As for why the fedora instructions install the executable into normal bin, that's because you run into selinux problems there too when it's in /usr/local/bin , but problems that were more complicated than my tiny selinux knowledge can deal with.
policycoreutils-python-utils is needed for semanage.
=> Added Fedora Instructions

content/relay-operations/technical-setup/bridge/openbsd/contents.lr
Hi There,
This is a PR to update the OpenBSD Tor bridge setup instructions with a few additional steps I had to perform to get it working. Using the existing instructions on a fresh installation of OpenBSD 6.5, running `rcctl start tor` gave me `tor(failed)` and the service failed to start.
The main errors when using the existing instructions I ran into:
```
[warn] Directory /root/.tor cannot be read: Permission denied
```
Tor was, by default, trying to write its data to `/root/.tor`. Since the existing instructions configure tor to launch as user `_tor`, this error makes sense since `_tor` doesn't have any access to /root by default. I fixed this by specifying `DataDirectory /var/tor`, which seems to be created by default after installing the `tor` package. It also is owned by `_tor` by …
=> Fix OpenBSD tor bridge instructions (data dir + logging perms)

README.md
The heading wasn't being rendered correctly.
Also removed redundant link text from the community portal link as links starting with http(s) are automatically hyperlinked in markdown.
=> Fix Heading in README

content/onion-services/setup/contents.lr, databags/pagenav+en.ini
Improves https://dip.torproject.org/web/community/issues/60
I wasn't sure if the correct pronunciation of .onion is onion or _dot onion_ since that affects whether it's an .onion or a .onion so that's unchanged.
Followed the terminology guidelines specified on the linked dip issue.
=> Improve Onion Services Terminology Consistency

content/relay-operations/technical-setup/bridge/dragonflybsd/contents.lr, content/relay-operations/technical-setup/bridge/netbsd/contents.lr
**DragonflyBSD**
- dfbsd is based on FreeBSD, and still keeps its default settings/paths;
- packages names and most configurations are just the same as fbsd;
- obfs4 is available! we can have more diverse bridges running.
**NetBSD**
- of course it runs NetBSD ]:-)
=> building bridges with DragonflyBSD, and NetBSD

content/relay-operations/contents.lr
Everything other than the O in operations is capital in headings.
And it is capital in the nav bar
=> Make Capitalization Consistent

README.md
With "cd lego..." instead of "cd community/lego...", I get an error;  `bash: cd: lego: No such file or directory`
=> Adding file location

content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr, content/relay-operations/technical-setup/bridge/fedora/contents.lr, content/relay-operations/technical-setup/guard/centosrhel/contents.lr, content/relay-operations/technical-setup/guard/fedora/contents.lr
It has details on how to install the Tor package from the
rpm.torproject.org repository.
Based on https://support.torproject.org/rpm/
=> Updates relay operation setup for Fedora/CentOS/RHEL

content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr, content/relay-operations/technical-setup/bridge/fedora/contents.lr, content/relay-operations/technical-setup/bridge/openbsd/contents.lr, content/relay-operations/technical-setup/exit/contents.lr, content/user-research/become-tester/contents.lr
[Find and fix header with two colors](https://gitlab.torproject.org/torproject/web/community/-/issues/129)
-----
Added `color: primary` to the following files:
* `/community/content/relay-operations/technical-setup/bridge/openbsd/contents.lr`
* `/community/content/relay-operations/technical-setup/exit/contents.lr`
* `/community/content/user-research/become-tester/contents.lr`
Deleted redundant `color: primary` in the following files:
* `/community/content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr`
* `/community/content/relay-operations/technical-setup/bridge/fedora/contents.lr`
=> Find and fix header with two colors

templates/sidenav.html
[Chevron Icon Collapsed Should Show First When Page Loads](https://gitlab.torproject.org/torproject/web/community/-/issues/137)
------
=> Fix chevron icon

content/relay-operations/types-of-relays/contents.lr
[Pluggable Transport Links to 2019 Site Instead of TB-Manual](https://gitlab.torproject.org/tpo/web/community/-/issues/140)
In the [`content/relay-operations/types-of-relays/contents.lr file`](https://gitlab.torproject.org/tpo/web/community/-/blob/master/content/relay-operations/types-of-relays/contents.lr), on line 63 change
```
[Pluggable transports](https://2019.www.torproject.org/docs/pluggable-transports.html.en)
```
to
```
[Pluggable transports](https://tb-manual.torproject.org/circumvention/)
```
=> Update pluggable transport link

content/onion-services/advanced/onion-location/contents.lr
The documentation was missing instructions for Caddy 2, which is the most painless way to run add an `onion-locator`. Caddy 2 automatically provisions SSL/TLS certificate via LetsEncrypt and runs the HTTP-to-HTTPS redirect by default, both of which are requirements for the Onion Location header.
=> Add instructions for Caddy 2

content/relay-operations/technical-setup/guard/centosrhel/updates/contents.lr
The tool for auto upgrade is changed from `yum-cron` to `dnf-automatic` in RHEL 8/ CentOS 8/ Fedora22.
A session on how to setup `dnf-automatic` in RHEL 8/ CentOS 8 is added, which is based on https://fedoraproject.org/wiki/AutoUpdates#Fedora_22_or_later_versions
=> Add instruction on enable autoupdate in RHEL 8

content/relay-operations/technical-setup/bridge/debian-ubuntu/contents.lr
Added to the docs that Ubuntu focal supports obfs4proxy package installation. 
Addressing the issue : https://gitlab.torproject.org/tpo/web/community/-/issues/185
=> Add Focal Fossa as supported release in how to install obfs4proxy

templates/outreach-talk.html
Addressing the issue : Parentheses missing in definition of "501(c)(3) nonprofit organization"
=> Added parentheses

content/relay-operations/technical-setup/bridge/fedora/contents.lr
You don't have to build obfs4 from source on Fedora since it is already packaged and installable with dnf.
However I'm not sure if you need run
```
/sbin/restorecon -v `which obfs4proxy`
```
or not. I did not run it and the port seems to be reachable (tested with https://bridges.torproject.org/scan/).
The package also includes a file `/etc/tor/obfs4.torrc` which maybe could be used to simplify the setup process even further.
=> [Fedora instructions] Use system package obfs4

content/relay/community-resources/good-bad-isps/contents.lr
Added Privex Inc. - https://www.privex.io/tor-exit-policy/ - added to Germany, FInland, and Sweden
I am the CEO of Privex Inc. - We allow exits in Sweden (and soon the Netherlands), and relays/bridges in all other regions.
=> Added Privex to Finland, Germany, and Sweden
