- content/relay-operations/technical-setup/bridge/fedora/contents.lr
See title, hopefully I did everything correctly!
> Added Fedora Guide

- templates/macros/footer.html
will-fix https://dip.torproject.org/web/tpo/issues/39 partly
> Update trademark FAQ link in footer

- content/relay-operations/community-resources/contents.lr
Update link for Tor FAQ to Support portal.
> Update link for Tor FAQ

- content/relay-operations/community-resources/eff-tor-legal-faq/contents.lr
https://dip.torproject.org/torproject/web/community/issues/111
> Fix 404 error #111

- content/relay-operations/community-resources/relay-associations/contents.lr
- databags/relay-associations.ini
- templates/relay-associations.html
> Create page to list relay-associations

- content/localization/pick-a-project/contents.lr
> Fix Transifex link to Community portal

- README.md
- Periods were added to the end of instructions, to keep them consistent throughout.
- Corrections were made from "e.g" to "e.g." throughout the text.
> Normalize punctuation usage

- content/onion-services/advanced/client-auth/contents.lr
- Change language from "onion service version X" to "vX onion service" to fit in with other pages
- Reword a few phrases to make them less awkward to read
- Add missing spaces and colons
> Clean up a few phrases

- content/relay-operations/technical-setup/bridge/windows/contents.lr
[[Relay] How-to setup relay in Windows](https://gitlab.torproject.org/tpo/web/community/-/issues/83)
-----
> Add bridge deploy for windows

- content/relay-operations/technical-setup/post-install/contents.lr
Added another operating system and its keys location.
> Add keys folder location Fedora

- content/relay-operations/technical-setup/bridge/windows/contents.lr
[Bridge on Windows Directions Needs to Bring Awareness of Version of the Tor Browser](https://gitlab.torproject.org/tpo/web/community/-/issues/146)
Add `(version depends on your computer)` and change URL to `https://www.torproject.org/download/languages/`
> Refine Windows bridge instructions

- content/relay-operations/community-resources/good-bad-isps/contents.lr
Add Telmex a Good Experiences in Mexico  and update info related with Axtel.
Thanks, Jacobo
> Add Telmex a Good Experiences in Mexico 

- content/relay-operations/community-resources/bad-relays/contents.lr
> Update dead links

- content/relay-operations/community-resources/good-bad-isps/contents.lr
Add Mega Cable to Good Experiences ISP in Mexico
Thanks, Jacobo
> Add Mega Cable to Good Experiences ISP in Mexico

- content/relay-operations/community-resources/good-bad-isps/contents.lr
Removed cyberbunker because they exist no more, updated alexhost policy
> Remove cyberbunker + update alexhost

- content/relay-operations/technical-setup/post-install/contents.lr
https://gitlab.torproject.org/tpo/web/community/-/issues/149
> Add bold to ipv6 troubleshooting

- content/relay-operations/community-resources/good-bad-isps/contents.lr
Added my experience with Cloudvider, Hivelocity, and Swiss Made Host.
> Added 3 ISPs

- content/relay-operations/technical-setup/bridge/contents.lr
Add precautions when turning a non-bridge rely into a bridge.
(relative to this thread : https://lists.torproject.org/pipermail/tor-relays/2020-September/018955.html)
> Turning existing relay into bridge

- content/localization/becoming-tor-translator/contents.lr
issue: https://gitlab.torproject.org/tpo/web/community/-/issues/106
Fixed display of screenshots so that each image appears on a new line after the text.
> fixed screenshot display issue in fullscreen

- content/relay-operations/community-resources/bad-relays/contents.lr
> Update contents.lr Typing error correction

- content/gsoc/cloudflare-captcha-monitoring/contents.lr
- content/relay-operations/community-resources/tor-abuse-templates/contents.lr
issue: https://gitlab.torproject.org/tpo/web/support/-/issues/131#note_2712213
> replace CAPTCHA with Captcha

- content/gsoc/cloudflare-captcha-monitoring/contents.lr
- content/gsoc/ooni-explorer-findings/contents.lr
- content/gsoc/ooni-explorer-testing/contents.lr
- content/gsoc/ooni-probe-desktop-custom-urls/contents.lr
- content/gsoc/ooni-probe-experiments/contents.lr
- content/gsoc/privacy-aware-geo-lookup/contents.lr
- content/gsoc/snowflake-android-proxy/contents.lr
- models/project.ini
- templates/gsoc.html
1. Clean up old projects
2. Update model to point to completed projects
> Gsoc Updates

- content/gsoc/gettor-distribution/contents.lr
- content/gsoc/onion-toolbox/contents.lr
- content/gsoc/ooni-explorer-testing/contents.lr
- content/gsoc/ooni-probe-desktop-custom-urls/contents.lr
- content/gsoc/ooni-probe-experiments/contents.lr
- content/gsoc/privacy-aware-geo-lookup/contents.lr
- content/gsoc/privacy-friendly-web/contents.lr
- content/gsoc/salmon-bridge-distribution/contents.lr
- content/gsoc/tor-keygen/contents.lr
- content/gsoc/tor-relay-ipv6-support/contents.lr
- content/gsoc/tor-weather/contents.lr
- Add OONI projects back in
- Remove inactive projects/mentors
> Gsoc 2021 updates

- content/gsoc/alexa-captcha-monitoring/contents.lr
Add a project to build upon GSoC 2020's Cloudflare Captcha monitoring project
> Add new project to list of potential GSoC projects

- content/gsoc/onion-balance-v3/contents.lr
> Add Onion Balance v3 enhancements project to list of GSoC projects

- content/gsoc/ooni-explorer-code-quality/contents.lr
- content/gsoc/ooni-geoip-accuracy/contents.lr
- content/gsoc/ooni-probe-testing/contents.lr
- content/gsoc/ooni-roaming-test/contents.lr
> Add GSoC 2021 OONI Projects

- content/localization/translation-problem/contents.lr
Issue: https://gitlab.torproject.org/tpo/web/community/-/issues/158
Updated "Report a problem with a translation" page
> Updated "Report a problem with a translation" page

- content/relay-operations/community-resources/good-bad-isps/contents.lr
> Update GoodBad ISPs

- content/relay-operations/community-resources/good-bad-isps/contents.lr
Addressing the issue: https://gitlab.torproject.org/tpo/web/community/-/issues/194
> [Relays] Update ticket number and link

- content/relay-operations/technical-setup/guard/fedora/contents.lr
Addressing the issue : https://gitlab.torproject.org/tpo/web/community/-/issues/170
> Added fedora instructions

- content/relay-operations/technical-setup/bridge/centos-rhel-opensuse/contents.lr
- content/relay-operations/technical-setup/bridge/debian-ubuntu/contents.lr
- content/relay-operations/technical-setup/bridge/docker/contents.lr
- content/relay-operations/technical-setup/bridge/dragonflybsd/contents.lr
- content/relay-operations/technical-setup/bridge/fedora/contents.lr
- content/relay-operations/technical-setup/bridge/freebsd/contents.lr
- content/relay-operations/technical-setup/bridge/netbsd/contents.lr
- content/relay-operations/technical-setup/bridge/openbsd/contents.lr
- content/relay-operations/technical-setup/bridge/post-install/contents.lr
Addressing the issue : https://gitlab.torproject.org/tpo/web/community/-/issues/197
Added unique keys in alphabetical order.
> Fix #197 [Bridge] Duplicate keys

- templates/relay-operations.html
> Added space

- databags/onions.ini
Fixes [GitLab issue 207](https://gitlab.torproject.org/tpo/web/community/-/issues/207); first contribution!
> Update Privacy International .onion

- databags/onions.ini
This is an amendment to the Issue [209](https://gitlab.torproject.org/tpo/web/community/-/issues/209).
> the fb onion service link updated

- content/relay/community-resources/good-bad-isps/contents.lr
* Add BuyVM to Luxembourg.
* Update BuyVM info, I've gotten 0 abuse notices with the only 3 ports they require blocked.
* Remove random ` characters?
> Add BuyVM to Luxembourg & Update info

- content/relay/setup/snowflake/standalone/contents.lr
Hi, 
I changed for the url of the docker image. Since the previous one required authentication. 
Thanks,  Jacobo
> Change by url without authentication

- content/relay/getting-help/contents.lr
https://gitlab.torproject.org/tpo/web/community/-/issues/227
> Add Support portal / relay-operators
